{ pkgs, ... }:
{
  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    adbfs-rootless
    android-tools
    anki
    application-title-bar
    aspell
    aspellDicts.en
    aspellDicts.en-computers
    aspellDicts.en-science
    aspellDicts.pl
    bc
    blueman
    calc
    cargo
    clang
    clisp
    cmake
    coppwr
    coursier
    dconf
    dconf-editor
    discord
    docker
    docker-compose
    dosbox-x
    dwarf-fortress
    easyeffects
    elementary-xfce-icon-theme
    emacs-pgtk
    ffmpeg
    file
    firefox
    flatpak-builder
    foot
    fzf
    gcc
    ghc
    gimp3
    git
    glib.dev
    gnumake
    gnupg
    go-font
    graphviz
    grim
    gsettings-desktop-schemas
    gtk4.dev
    helix
    htop
    hunspell
    hunspellDicts.pl_PL
    imagemagick
    inkscape-with-extensions
    inotify-tools
    jdk
    jetbrains.idea
    jujutsu
    #kdePackages.kdeconnect-kde
    kdePackages.plasma-keyboard
    krita
    ktailctl
    lean4
    libinput
    libnotify
    libreoffice-qt6-fresh
    lisgd
    lm_sensors
    maliit-keyboard
    metals
    morewaita-icon-theme
    mousepad
    nasm
    nicotine-plus
    nixfmt
    nixfmt-tree
    nodejs
    nvd
    nwg-drawer
    pandoc
    pango
    phinger-cursors
    pkg-config
    plasma-panel-colorizer
    ptyxis
    pwvucontrol
    python3
    qemu
    racket
    rakudo
    rnote
    rofi
    rofi
    satty
    sbt
    scala-cli
    signal-desktop
    slurp
    smartmontools
    squeekboard
    sshfs
    supersonic
    swaybg
    swaylock
    swaynotificationcenter
    sxiv
    texlive.combined.scheme-medium
    thunar
    thunar-volman
    unrar
    unzip
    usbutils
    uv
    veloren
    vim
    virtio-win
    visualvm
    vlc
    wabt
    wasmtime
    waybar
    wf-recorder
    wireguard-tools
    wl-clipboard
    wtype
    wvkbd
    xfce4-appfinder
    xournalpp
    xsane
    xwayland-satellite
    zathura
    zip
    zlib
    zotero
  ];

  fonts.packages = with pkgs; [
    fira-code
    fira-code-symbols
    liberation_ttf
    mplus-outline-fonts.githubRelease
    nerd-fonts."m+"
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
  ];
}
